# -*- coding: utf-8 -*-
"""capturing image

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18awIXIf8au9Dv2-tRD7cSgVeDiuRRNse
"""

import cv2

camera_port=0    #camera 0 is laptop camera
ramp_frames=30    #30 frames pause before taking a picture to adjust
camera=cv2.VideoCapture(camera_port)  #establishesthe camera

#captures a single image from the camera and return it in PIL format
def get_image():
  retval,im=camera.read()
  return im

for i in range(ramp_frames):
  temp=get_image()
print("Capturing image...")

#takes the picture
camera_capture=get_image()
file='test_image.png'
cv2.imwrite(file, camera_capture)

#releases the camera
del camera
print("picture taken.")

